qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr1
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr2
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr3
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr4
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr5
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr6
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr7
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr8
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr9
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr10
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr11
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr12
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr13
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr14
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr15
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr16
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr17
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr18
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr19
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr20
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr21
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chr22
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chrX
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split.sh chrY
