qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr1
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr2
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr3
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr4
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr5
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr6
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr7
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr8
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr9
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr10
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr11
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr12
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr13
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr14
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr15
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr16
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr17
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr18
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr19
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr20
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr21
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chr22
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chrX
qsub /home/aiokada/sandbox/nanopore/script/COLO829/singularity_medaka_cpu_split_mem32.sh chrY
