qsub -l mem_req=80G,s_vmem=80G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr1
qsub -l mem_req=24G,s_vmem=24G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr2
qsub -l mem_req=24G,s_vmem=24G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr3
qsub -l mem_req=24G,s_vmem=24G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr4
qsub -l mem_req=8G,s_vmem=8G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr5
qsub -l mem_req=12G,s_vmem=12G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr6
qsub -l mem_req=24G,s_vmem=24G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr7
qsub -l mem_req=12G,s_vmem=12G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr8
qsub -l mem_req=12G,s_vmem=12G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr9
qsub -l mem_req=8G,s_vmem=8G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr10
qsub -l mem_req=8G,s_vmem=8G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr11
qsub -l mem_req=8G,s_vmem=8G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr12
qsub -l mem_req=12G,s_vmem=12G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr13
qsub -l mem_req=8G,s_vmem=8G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr14
qsub -l mem_req=8G,s_vmem=8G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr15
qsub -l mem_req=24G,s_vmem=24G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr16
qsub -l mem_req=8G,s_vmem=8G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr17
qsub -l mem_req=8G,s_vmem=8G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr18
qsub -l mem_req=8G,s_vmem=8G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr19
qsub -l mem_req=8G,s_vmem=8G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr20
qsub -l mem_req=12G,s_vmem=12G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr21
qsub -l mem_req=8G,s_vmem=8G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chr22
qsub -l mem_req=8G,s_vmem=8G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chrX
qsub -l mem_req=8G,s_vmem=8G /home/aiokada/sandbox/nanopore/script/COLO829/shell_diff_nanopolish.sh chrY
